from .detector import DETECTOR_INSTRUCTION
from .generator import GENERATOR_INSTRUCTION
from .recommender import RECOMMENDER_INSTRUCTION
from .scanner import SCANNER_INSTRUCTION

__all__ = [
    "DETECTOR_INSTRUCTION",
    "GENERATOR_INSTRUCTION",
    "RECOMMENDER_INSTRUCTION",
    "SCANNER_INSTRUCTION",
]
