from .detector import DETECTOR_INSTRUCTION
from .generator import GENERATOR_INSTRUCTION
from .scanner import SCANNER_INSTRUCTION

__all__ = ["DETECTOR_INSTRUCTION", "GENERATOR_INSTRUCTION", "SCANNER_INSTRUCTION"]
